(#74)(ENGTASKS-3605) Update ReadMe and Vagrantfile in preperation for release of new box version with Hyper-V provider
chocolatey-community/chocolatey-test-environment pull request #77
Opened 2024-06-17 23:36 UTC by Windos

## Description Of Changes

This PR includes two small tweaks to the Vagrantfile specific to the Hyper-V provider that came out of testing using Hyper-V to run the Chocolatey Test Environment. Specifically, it increases the timeout for getting an IP address when first booting the image and it also sets the "maximum memory" to `nil` so that the user can specify any amount of memory as allowed by their available resources.

It also updates the ReadMe with information specific to running this testing environment under Hyper-V, including warning about the limitations that may be encountered while doing so.

## Motivation and Context

We're about to release v3.2.0 of the Vagrant box used by this test environment and re-introduce a Hyper-V version of the box.

## Testing

These changes come as a result of testing the new Hyper-V provider version of the test-environment box (v3.2.0).

### Operating Systems Testing

N/A

## Change Types Made

* [ ]  Bug fix (non-breaking change).
* [x]  Feature / Enhancement (non-breaking change).
* [ ]  Breaking change (fix or feature that could cause existing functionality to change).
* [x]  Documentation changes.
* [ ]  PowerShell code changes.

## Change Checklist

* [x]  Requires a change to the documentation.
* [x]  Documentation has been updated.
* [ ]  Tests to cover my changes, have been added.
* [ ]  All new and existing tests passed?
* [ ]  PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

* #74
* ENGTASKS-3605

2024-06-19 14:54 UTC, pauby requested changes
Just a few changes @Windos. I know some of them are not anything you have changed in this PR. But I feel we should make the changes while we're in here.

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
> +> It is recommended to favour running the Chocolatey Test Environment under VirtualBox.
```suggestion
> It is recommended to favor running the Chocolatey Test Environment under VirtualBox.

```

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
> +> It is recommended to favour running the Chocolatey Test Environment under VirtualBox.
We should use US spelling.

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
> +     * The image downloaded the first time you run this command is specific to Hyper-V and so a large download will be required even if you've already downloaded the VirtualBox image
```suggestion
 1. Ensure setup above is complete, ignoring the need for VirtualBox.
 1. Enable the Hyper-V feature:
     * Open a PowerShell console as Administrator.
     * Run `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All -All`.
     * Restart Windows.
 1. Follow the general instructions to [prepare the testing environment](#preparing-the-testing-environment), swapping the default `vagrant up` command with `vagrant up --provider=hyperv`.
     * The Hyper-V image, downloaded the first time you run command is very large (> 5GB) and specific to Hyper-V.
```

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
> + * The verifier only runs against Windows 2019 currently. This repo is adding more boxes as they become available.
```suggestion
 * Package Verifier only runs against Windows Server 2019, currently.

```

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
>  There are a couple of difference between the [verifier service](https://docs.chocolatey.org/en-us/community-repository/moderation/package-verifier) and this environment.
```suggestion
There are a couple of difference between the [Package Verifier service](https://docs.chocolatey.org/en-us/community-repository/moderation/package-verifier) and this environment.

```

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
>   * The verifier times out on waiting for a command after 12 minutes.
```suggestion
 * Package Verifier times out on waiting for a command after 12 minutes.

```

2024-06-19 14:54 UTC, pauby commented on ReadMe.md
>   * Synced folders are different - the verifier syncs the .chocolatey folder to gather the package information files.
```suggestion
 * Synced folders are different - Package Verifier syncs the `.chocolatey` folder to gather the package information files.

```

2024-06-19 14:54 UTC, pauby commented
@Windos I don't think we should merge this in until the box is on the Vagrant Cloud?

2024-06-20 05:23 UTC, Windos commented
Thanks for the review and suggested edits, @pauby, I agreed with and applied all of them.

Agreed that this should be merged at the same time as the blog post and the boxes are released (those are ready to go now, thankfully)

2024-06-20 10:00 UTC, pauby approved these changes

2024-06-20 10:04 UTC, merged

2024-06-20 10:04 UTC, pauby commented
Thanks @Windos for getting this updated!